dwp/dataworks-admin-utils

README.md, ci/vars.yml
Readme updates now pipelines are confirmed
=> Readme updates now pipelines are confirmed

.github/workflows/pr.yml, utils/ami-cleanup/ami_cleanup.py, utils/lambda-cleanup/aws_utility.py, utils/lambda-cleanup/lambda_prune.py
Add Black format PR job to allow for Python code to be automatically formatted, and changes pushed if there are any.
=> Add Python Black format pr job

README.md, ci/uc-data-load/groups-uc-data-load.yml, ci/uc-data-load/jobs/development.yml, ci/uc-data-load/jobs/preprod.yml, ci/uc-data-load/jobs/production-import-only-skip-records.yml, ci/uc-data-load/jobs/production-import-only.yml, ci/uc-data-load/jobs/production-manifest-only-skip-records.yml, ci/uc-data-load/jobs/production-manifest-only.yml, ci/uc-data-load/jobs/production-skip-records.yml, ci/uc-data-load/jobs/production.yml, ci/uc-data-load/jobs/qa.yml
DW-4427 add the skip records jobs to the pipeline and rename existing jobs and groups to make more sense. Update README with optional override details.
=> Dw 4427 add skip jobs

ci/uc-data-load/jobs/production-import-only.yml
DW-4568 latest uc import 14-07-2020 needs cut-off date.
=> DW-4568 latest uc import 14-07-2020 needs cut-off date

ci/uc-data-load/jobs/production-import-only-skip-records.yml, ci/uc-data-load/jobs/production-import-only.yml, ci/uc-data-load/jobs/production-manifest-only-skip-records.yml, ci/uc-data-load/jobs/production-manifest-only.yml, ci/uc-data-load/jobs/production-skip-records.yml, ci/uc-data-load/jobs/production.yml
Update per record to false for all uc data load jobs
=> Update per record to false for all uc data load jobs

ci/scale-down-services/groups-scale-down-services.yml, ci/scale-down-services/jobs/dev-scale-down-k2hb.yml, ci/scale-down-services/jobs/integration-scale-down-k2hb.yml, ci/scale-down-services/jobs/preprod-scale-down-k2hb.yml, ci/scale-down-services/jobs/prod-scale-down-k2hb.yml, ci/scale-down-services/jobs/qa-scale-down-k2hb.yml, ci/scale-up-services/groups-scale-up-services.yml, ci/scale-up-services/jobs/dev-scale-up-k2hb.yml, ci/scale-up-services/jobs/integration-scale-up-k2hb.yml, ci/scale-up-services/jobs/preprod-scale-up-k2hb.yml, ci/scale-up-services/jobs/prod-scale-up-k2hb.yml, ci/scale-up-services/jobs/qa-scale-up-k2hb.yml
Scale up and down pipelines for k2hb on ec2
=> Scale up and down pipelines for k2hb on ec2

ci/generate-snapshots/groups-generate-snapshots.yml, ci/generate-snapshots/jobs/production-nightly-generate-and-send.yml, ci/generate-snapshots/meta-generate-snapshots.yml, ci/generate-snapshots/resources-generate-snapshots.yml
Add nightly send job for HTME and add clearing S3 steps
=> Add nightly send job for HTME and add clearing S3 steps

ci/ami-cleanup/meta.yml, utils/ami-cleanup/ami_cleanup.py
removes need for profiles to support AWS Concourse assuming roles.
=> Remove aws profile

README.md, ci/send-snapshots/jobs/production-reprocess-full-snapshots.yml
Add details of available override that was missing
=> Add details of available override that was missing

README.md
Allow correlation id override for re-running nightly failed topics
=> Allow correlation id override for re-running nightly failed topics

ci/generate-snapshots/jobs/production-generate-full-snapshots.yml, ci/manage-ecs-services/meta-manage-ecs-services.yml
Use the new output locations for manage ecs services pipeline
=> Use the new output locations

ci/scale-down-services/jobs/prod-scale-down-k2hb.yml, ci/scale-down-services/resources-scale-down-services.yml, ci/scale-up-services/jobs/prod-scale-up-k2hb.yml, ci/scale-up-services/resources-scale-up-services.yml
Scale up and down k2hb every night
=> Scale up and down k2hb every night

ci/generate-snapshots/jobs/production-nightly-generate-and-send.yml
Add task names for the nightly generate and send
=> Add task names for the nightly generate and send

ci/manage-ecs-services/meta-manage-ecs-services.yml
Fix the trim reconciler service scale up jobs
=> Fix the trim reconciler service scale up jobs

README.md
Add skip overrides to hdl pipeline
=> Add skip overrides to hdl pipeline

ci/hbase-data-ingestion/meta-hbase-data-ingestion.yml
More duration increases for long running jobs
=> More duration increases for long running jobs

ci/generate-snapshots/jobs/production-generate-full-snapshots.yml
DW-4860 do not send snapshots to Crown
=> DW-4860 do not send snapshots to Crown

Makefile, ci/manage-ecs-services/groups-manage-ecs-services.yml
=> organise the standard way

Makefile, aviator-ami-cleanup.yml, aviator-generate-snapshots.yml, aviator-hbase-data-ingestion.yml, aviator-lambda-cleanup.yml, aviator-manage-ecs-services.yml, aviator-manage-environments.yml, aviator-scale-down-services.yml, aviator-scale-up-services.yml, aviator-send-snapshots.yml, aviator-terraform-taint.yml
Move all pipelines to utility team
=> Move all pipelines to utility team

ci/manage-ecs-services/meta-manage-ecs-services.yml
Fix the restart jobs which are also not working with multiple service arns
=> Fix the restart jobs which are also not working with multiple service arns

ci/manage-ecs-services/groups-manage-ecs-services.yml, ci/manage-ecs-services/jobs/manage-audit-reconciliation.yml, ci/manage-ecs-services/jobs/restart-k2s3.yml, ci/manage-ecs-services/meta-manage-ecs-services.yml
=> Add audit reconciler jobs

ci/scale-up-services/jobs/qa-scale-up-k2hb.yml, ci/scale-up-services/jobs/qa-scale-up-kafka-stub.yml
Fix the wrong job set to scale up
=> Fix the wrong job set to scale up

README.md, ci/hbase-data-ingestion/jobs/corporate-data-load/production.yml, ci/hbase-data-ingestion/meta-hbase-data-ingestion.yml
Setup the CDL pipeline to load audit data and remove unused HDL overrides
=> Setup the CDL pipeline to load audit data and remove unused HDL overrides

ci/hbase-data-ingestion/meta-hbase-data-ingestion.yml
Fix incorrectly named variable
=> Fix incorrectly named variable

ci/hbase-data-ingestion/meta-hbase-data-ingestion.yml
Add more logging and fix the path to the outputs
=> Add more logging and fix the path to the outputs

ci/hbase-data-ingestion/meta-hbase-data-ingestion.yml
Max timeout for data load jobs
=> Max timeout for data load jobs

README.md
=> Add new override to README

ci/scale-down-services/groups-scale-down-services.yml, ci/scale-down-services/jobs/dev-scale-down-ingestion-ecs-cluster.yml, ci/scale-down-services/jobs/integration-scale-down-ingestion-ecs-cluster.yml, ci/scale-down-services/jobs/preprod-scale-down-ingestion-ecs-cluster.yml, ci/scale-down-services/jobs/prod-scale-down-ingestion-ecs-cluster.yml, ci/scale-down-services/jobs/qa-scale-down-ingestion-ecs-cluster.yml, ci/scale-up-services/groups-scale-up-services.yml, ci/scale-up-services/jobs/dev-scale-up-ingestion-ecs-cluster.yml, ci/scale-up-services/jobs/integration-scale-up-ingestion-ecs-cluster.yml, ci/scale-up-services/jobs/preprod-scale-up-ingestion-ecs-cluster.yml, ci/scale-up-services/jobs/prod-scale-up-ingestion-ecs-cluster.yml, ci/scale-up-services/jobs/qa-scale-up-ingestion-ecs-cluster.yml
=> Add scale up scale down ingestion-ecs-cluster tasks

ci/hbase-data-ingestion/groups-hbase-data-ingestion.yml, ci/hbase-data-ingestion/jobs/historic-data-import/preprod-import-only.yml, ci/hbase-data-ingestion/jobs/historic-data-import/preprod-manifest-only.yml, ci/send-snapshots/groups-send-snapshots.yml, ci/send-snapshots/jobs/preprod-reprocess-full-snapshots.yml, ci/send-snapshots/jobs/preprod-reprocess-incremental-snapshots.yml, ci/send-snapshots/jobs/production-reprocess-incremental-snapshots.yml
=> Preprod send jobs for snappy

ci/manage-ecs-services/groups-manage-ecs-services.yml, ci/manage-ecs-services/jobs/manage-sft-agent.yml, ci/manage-ecs-services/meta-manage-ecs-services.yml, ci/manage-ecs-services/resources-manage-ecs-services.yml, ci/shared/meta.yml
=> Add SFT Agent manage ECS tasks

ci/hbase-data-ingestion/meta-hbase-data-ingestion.yml, ci/scale-down-services/jobs/dev-scale-down-ingestion-ecs-cluster.yml, ci/send-snapshots/meta-send-snapshots.yml, ci/shared/meta.yml, ci/terraform-taint/meta-terraform-taint.yml
TF13 upgrade and fix a resource name
=> TF13 upgrade and fix a resource name

aviator-repo-alerts.yml, ci/repo-alerts/groups-repo-alerts.yml, ci/repo-alerts/jobs/slack-notification.yml, ci/repo-alerts/jobs/update-pipeline.yml, ci/repo-alerts/meta-repo-alerts.yml, ci/repo-alerts/resources-repo-alerts.yml, ci/repo-alerts/resources_types.yml
=> Repo alerts pipeline for Slack notifications

Makefile, README.md, aviator-uc-feature-emr-admin.yml, ci/uc-feature-emr-admin/groups-uc-feature-emr-admin.yml, ci/uc-feature-emr-admin/jobs/admin/clear_dynamodb_row.yml, ci/uc-feature-emr-admin/jobs/admin/start.yml, ci/uc-feature-emr-admin/jobs/admin/stop.yml, ci/uc-feature-emr-admin/jobs/integration/admin/clear_dynamodb_row.yml, ci/uc-feature-emr-admin/jobs/integration/admin/start.yml, ci/uc-feature-emr-admin/jobs/integration/admin/stop.yml, ci/uc-feature-emr-admin/jobs/preprod/admin/clear_dynamodb_row.yml, ci/uc-feature-emr-admin/jobs/preprod/admin/start.yml, ci/uc-feature-emr-admin/jobs/preprod/admin/stop.yml, ci/uc-feature-emr-admin/jobs/production/admin/clear_dynamodb_row.yml, ci/uc-feature-emr-admin/jobs/production/admin/start.yml, ci/uc-feature-emr-admin/jobs/production/admin/stop.yml, ci/uc-feature-emr-admin/jobs/qa/admin/clear_dynamodb_row.yml, ci/uc-feature-emr-admin/jobs/qa/admin/start.yml, ci/uc-feature-emr-admin/jobs/qa/admin/stop.yml, ci/uc-feature-emr-admin/jobs/update_pipeline.yml, ci/uc-feature-emr-admin/meta-uc-feature-emr-admin.yml
Signed-off-by: Mark <mark.stevens@infinityworks.com>
=> added admin pipeline for uc feature emr pipeline

ci/mongo-latest-emr-admin/jobs/production/admin/start.yml
=> Add snapshot type to pipeline

aviator-pt-2-emr-admin.yml, ci/pt-2-emr-admin/groups-pt-2-emr-admin.yml, ci/pt-2-emr-admin/jobs/dev/admin/clear_dynamodb_row.yml, ci/pt-2-emr-admin/jobs/dev/admin/start.yml, ci/pt-2-emr-admin/jobs/dev/admin/stop.yml, ci/pt-2-emr-admin/jobs/integration/admin/clear_dynamodb_row.yml, ci/pt-2-emr-admin/jobs/integration/admin/start.yml, ci/pt-2-emr-admin/jobs/integration/admin/stop.yml, ci/pt-2-emr-admin/jobs/preprod/admin/clear_dynamodb_row.yml, ci/pt-2-emr-admin/jobs/preprod/admin/start.yml, ci/pt-2-emr-admin/jobs/preprod/admin/stop.yml, ci/pt-2-emr-admin/jobs/production/admin/clear_dynamodb_row.yml, ci/pt-2-emr-admin/jobs/production/admin/start.yml, ci/pt-2-emr-admin/jobs/production/admin/stop.yml, ci/pt-2-emr-admin/jobs/qa/admin/clear_dynamodb_row.yml, ci/pt-2-emr-admin/jobs/qa/admin/start.yml, ci/pt-2-emr-admin/jobs/qa/admin/stop.yml, ci/pt-2-emr-admin/jobs/update_pipeline.yml, ci/pt-2-emr-admin/meta-pt-2-emr-admin.yml
=> PT-2 Admin utils pipeline

aviator-pt-2-emr-admin.yml
=> Shift to utility team

Makefile, README.md, aviator-cyi-emr-admin.yml, ci/cyi-emr-admin/groups-cyi-emr-admin.yml, ci/cyi-emr-admin/jobs/dev/admin/clear_dynamodb_row.yml, ci/cyi-emr-admin/jobs/dev/admin/start.yml, ci/cyi-emr-admin/jobs/dev/admin/stop.yml, ci/cyi-emr-admin/jobs/integration/admin/clear_dynamodb_row.yml, ci/cyi-emr-admin/jobs/integration/admin/start.yml, ci/cyi-emr-admin/jobs/integration/admin/stop.yml, ci/cyi-emr-admin/jobs/preprod/admin/clear_dynamodb_row.yml, ci/cyi-emr-admin/jobs/preprod/admin/start.yml, ci/cyi-emr-admin/jobs/preprod/admin/stop.yml, ci/cyi-emr-admin/jobs/production/admin/clear_dynamodb_row.yml, ci/cyi-emr-admin/jobs/production/admin/start.yml, ci/cyi-emr-admin/jobs/production/admin/stop.yml, ci/cyi-emr-admin/jobs/qa/admin/clear_dynamodb_row.yml, ci/cyi-emr-admin/jobs/qa/admin/start.yml, ci/cyi-emr-admin/jobs/qa/admin/stop.yml, ci/cyi-emr-admin/jobs/update_pipeline.yml, ci/cyi-emr-admin/meta-cyi-emr-admin.yml, ci/cyi-emr-admin/resources-cyi-emr-admin.yml
=> Add CYI EMR admin pipeline

ci/pt-2-emr-admin/jobs/dev/admin/clear_dynamodb_row.yml, ci/pt-2-emr-admin/jobs/dev/admin/start.yml, ci/pt-2-emr-admin/jobs/dev/admin/stop.yml, ci/pt-2-emr-admin/jobs/integration/admin/clear_dynamodb_row.yml, ci/pt-2-emr-admin/jobs/integration/admin/start.yml, ci/pt-2-emr-admin/jobs/integration/admin/stop.yml, ci/pt-2-emr-admin/jobs/preprod/admin/clear_dynamodb_row.yml, ci/pt-2-emr-admin/jobs/preprod/admin/start.yml, ci/pt-2-emr-admin/jobs/preprod/admin/stop.yml, ci/pt-2-emr-admin/jobs/production/admin/clear_dynamodb_row.yml, ci/pt-2-emr-admin/jobs/production/admin/start.yml, ci/pt-2-emr-admin/jobs/production/admin/stop.yml, ci/pt-2-emr-admin/jobs/qa/admin/clear_dynamodb_row.yml, ci/pt-2-emr-admin/jobs/qa/admin/start.yml, ci/pt-2-emr-admin/jobs/qa/admin/stop.yml, ci/pt-2-emr-admin/meta-pt-2-emr-admin.yml
Signed-off-by: Chris Scott-Thomas <chrisscott-thomas@digital.uc.dwp.gov.uk>
=> dunno waht pd-2 is

aviator-analytical-env-admin.yml, ci/analytical-env-admin/jobs/rbac_admin/development.yml, ci/analytical-env-admin/jobs/rbac_admin/int.yml, ci/analytical-env-admin/jobs/rbac_admin/preprod.yml, ci/analytical-env-admin/jobs/rbac_admin/prod.yml, ci/analytical-env-admin/jobs/rbac_admin/qa.yml, ci/analytical-env-admin/jobs/taint/dev.yml, ci/analytical-env-admin/jobs/taint/int.yml, ci/analytical-env-admin/jobs/taint/preprod.yml, ci/analytical-env-admin/jobs/taint/prod.yml, ci/analytical-env-admin/jobs/taint/qa.yml, ci/analytical-env-admin/meta-analytical-env-admin.yml, ci/analytical-env-admin/resources-analytical-env-admin.yml, ci/shared/resourcetypes.yml
=> Fix pipeline

ci/mongo-latest-emr-admin/meta-mongo-latest-emr-admin.yml
=> Fix mongo latest prefix

ci/hbase-data-ingestion/jobs/corporate-data-load/development.yml, ci/hbase-data-ingestion/jobs/corporate-data-load/integration.yml, ci/hbase-data-ingestion/jobs/corporate-data-load/preprod.yml, ci/hbase-data-ingestion/jobs/corporate-data-load/production.yml, ci/hbase-data-ingestion/jobs/corporate-data-load/qa.yml, ci/hbase-data-ingestion/jobs/historic-data-import/development.yml, ci/hbase-data-ingestion/jobs/historic-data-import/preprod-import-only.yml, ci/hbase-data-ingestion/meta-hbase-data-ingestion.yml
=> Fix CDL pipeline

ci/adg-emr-admin/meta-adg-emr-admin.yml, ci/analytical-env-admin/meta-analytical-env-admin.yml, ci/clive-emr-admin/meta-clive-emr-admin.yml, ci/mongo-latest-emr-admin/meta-mongo-latest-emr-admin.yml, ci/pdm-emr-admin/meta-pdm-emr-admin.yml, ci/uc-feature-emr-admin/meta-uc-feature-emr-admin.yml
Removes use of deprecated handler
=> Change emr launcher payload for various jobs
